### PR TITLE
fix bug in scheduler, rescheduling jobs immediately

### LINKED ISSUE #20: Bug in scheduler
```
package main

import (
	"fmt"
	"time"

	"github.com/go-co-op/gocron"
)

func task() {
	fmt.Println(time.Now())
}

func main() {
	s1 := gocron.NewScheduler(time.UTC)
	s1.Every(10).Seconds().Do(task)
	<-s1.Start() // starts running (blocks current thread)
}

```
```
go run main.go
2020-03-31 23:10:10.5018339 -0500 CDT m=+10.003605201
2020-03-31 23:10:20.5028812 -0500 CDT m=+20.004652501
2020-03-31 23:10:30.501854 -0500 CDT m=+30.003625301
2020-03-31 23:10:31.5013486 -0500 CDT m=+31.003119901
2020-03-31 23:10:41.5022159 -0500 CDT m=+41.003987201
2020-03-31 23:10:51.5013717 -0500 CDT m=+51.003143001
2020-03-31 23:10:52.5031395 -0500 CDT m=+52.004910801
2020-03-31 23:11:02.5020695 -0500 CDT m=+62.003840801
2020-03-31 23:11:03.5014576 -0500 CDT m=+63.003228901
2020-03-31 23:11:13.5016872 -0500 CDT m=+73.003458501
2020-03-31 23:11:23.5017684 -0500 CDT m=+83.003539701
2020-03-31 23:11:33.5013161 -0500 CDT m=+93.003087401
2020-03-31 23:11:34.508206 -0500 CDT m=+94.009977301
2020-03-31 23:11:44.5021093 -0500 CDT m=+104.003880601
2020-03-31 23:11:45.503181 -0500 CDT m=+105.004952301
2020-03-31 23:11:55.5017912 -0500 CDT m=+115.003562501
2020-03-31 23:11:56.5028593 -0500 CDT m=+116.004630601
2020-03-31 23:12:06.5013873 -0500 CDT m=+126.003158601
2020-03-31 23:12:07.5014535 -0500 CDT m=+127.003224801
2020-03-31 23:12:17.5013532 -0500 CDT m=+137.003124501
2020-03-31 23:12:18.5029237 -0500 CDT m=+138.004695001
2020-03-31 23:12:28.501378 -0500 CDT m=+148.003149301
2020-03-31 23:12:29.5012798 -0500 CDT m=+149.003051101
2020-03-31 23:12:39.5022707 -0500 CDT m=+159.004042001
2020-03-31 23:12:49.5018604 -0500 CDT m=+169.003631701
2020-03-31 23:12:50.5017803 -0500 CDT m=+170.003551601
2020-03-31 23:13:00.5019564 -0500 CDT m=+180.003727701
2020-03-31 23:13:10.5020875 -0500 CDT m=+190.003858801
2020-03-31 23:13:20.5016438 -0500 CDT m=+200.003415101
2020-03-31 23:13:21.5017742 -0500 CDT m=+201.003545501
2020-03-31 23:13:31.503144 -0500 CDT m=+211.004915301
2020-03-31 23:13:41.5014638 -0500 CDT m=+221.003235101
2020-03-31 23:13:42.5028217 -0500 CDT m=+222.004593001
2020-03-31 23:13:52.5013111 -0500 CDT m=+232.003082401
2020-03-31 23:13:53.5014415 -0500 CDT m=+233.003212801
2020-03-31 23:14:03.501239 -0500 CDT m=+243.003010301
2020-03-31 23:14:04.5013094 -0500 CDT m=+244.003080701
2020-03-31 23:14:14.5030847 -0500 CDT m=+254.004856001
2020-03-31 23:14:24.5019311 -0500 CDT m=+264.003702401
2020-03-31 23:14:25.5020085 -0500 CDT m=+265.003779801
```

### PR DESCRIPTION
**Pull request by JohnRoesler**
```
package main

import (
	"fmt"
	"time"

	"github.com/go-co-op/gocron"
)

func task() {
	fmt.Printf("Task time: %v\n", time.Now().UTC())
}

func main() {
	s1 := gocron.NewScheduler(time.UTC)
	s1.Every(2).Seconds().StartImmediately().Do(task)
	<-s1.Start() // starts running (blocks current thread)
}
```

Output:
```
Task time: 2020-04-10 05:13:40.606502 +0000 UTC
Task time: 2020-04-10 05:13:42.60736 +0000 UTC
Task time: 2020-04-10 05:13:44.608121 +0000 UTC
Task time: 2020-04-10 05:13:46.609026 +0000 UTC
Task time: 2020-04-10 05:13:48.606512 +0000 UTC
Task time: 2020-04-10 05:13:50.608894 +0000 UTC
Task time: 2020-04-10 05:13:52.606553 +0000 UTC
Task time: 2020-04-10 05:13:54.608598 +0000 UTC
Task time: 2020-04-10 05:13:56.606573 +0000 UTC
Task time: 2020-04-10 05:13:58.606552 +0000 UTC
Task time: 2020-04-10 05:14:00.608368 +0000 UTC
Task time: 2020-04-10 05:14:02.606641 +0000 UTC
Task time: 2020-04-10 05:14:04.608286 +0000 UTC
Task time: 2020-04-10 05:14:06.606737 +0000 UTC
Task time: 2020-04-10 05:14:08.608174 +0000 UTC
Task time: 2020-04-10 05:14:10.608141 +0000 UTC
Task time: 2020-04-10 05:14:12.606751 +0000 UTC
Task time: 2020-04-10 05:14:14.607512 +0000 UTC
Task time: 2020-04-10 05:14:16.606776 +0000 UTC
Task time: 2020-04-10 05:14:18.607749 +0000 UTC
Task time: 2020-04-10 05:14:20.606882 +0000 UTC
Task time: 2020-04-10 05:14:22.606922 +0000 UTC
Task time: 2020-04-10 05:14:24.608243 +0000 UTC
Task time: 2020-04-10 05:14:26.608399 +0000 UTC
Task time: 2020-04-10 05:14:28.607878 +0000 UTC
Task time: 2020-04-10 05:14:30.606958 +0000 UTC
Task time: 2020-04-10 05:14:32.607995 +0000 UTC
Task time: 2020-04-10 05:14:34.60762 +0000 UTC
Task time: 2020-04-10 05:14:36.607508 +0000 UTC
Task time: 2020-04-10 05:14:38.60877 +0000 UTC
Task time: 2020-04-10 05:14:40.609291 +0000 UTC
Task time: 2020-04-10 05:14:42.607145 +0000 UTC
Task time: 2020-04-10 05:14:44.608426 +0000 UTC
```

Closes #20

### CODE REVIEW

File: scheduler.go [hunk 1]
```diff
@@ -70,12 +70,9 @@ func (s *Scheduler) SetLocation(newLocation *time.Location) {
...
 // scheduleNextRun Compute the instant when this Job should run next
 func (s *Scheduler) scheduleNextRun(j *Job) error {
-	now := s.time.Now().In(s.loc)
-	if j.lastRun == s.time.Unix(0, 0) {
-		j.lastRun = now
-	}
+	now := s.time.NowRoundedDownToSeconds(s.loc)
 
-	if j.nextRun.After(now) {
+	if j.nextRun.Second() > now.Second() {
```
Comment (arjunmahishi) [inline scheduler.go:75]: Any reason for changing this?

Comment (Streppel) [reply scheduler.go:75]: @arjunmahishi it's because .After() considers nanoseconds while our implementation of .shouldRun() only considers seconds (it mutates the time using .Unix()), so we have two different time precisions within the scheduler.

I believe we should stick to using Unix here as well to compare the whole timestamp... One problem with this current implementation is that if we ommit comparing minutes and hours. Consider the following

nextRun = 10:20:35
now = 10:30:30

NextRun is not after now, but can you spot the seconds issue?

File: scheduler.go [hunk 2]
```diff
@@ -283,11 +294,16 @@ func (s *Scheduler) StartAt(t time.Time) *Scheduler {
...
 func (s *Scheduler) StartImmediately() *Scheduler {
 	job := s.getCurrentJob()
-	job.nextRun = s.time.Now().In(s.loc)
+	job.nextRun = s.time.NowRoundedDownToSeconds(s.loc)
 	job.startsImmediately = true
 	return s
 }
 
+// shouldRun returns true if the Job should be run now
+func (s *Scheduler) shouldRun(j *Job) bool {
```
Comment (Streppel) [inline scheduler.go:303]: nice, much better

File: scheduler.go (hunk 1 above)
Comment (JohnRoesler) [reply scheduler.go:75]: That's a good call out. Essentially we just want to compare full time stamps rounded to seconds. I'll udpate.

File: scheduler.go (hunk 2 above)
Comment (JohnRoesler) [reply scheduler.go:303]: yeah! had to change it because the job had no location concept, so it was setting it's next run in a different timezone which was messing with things

**Comment by JohnRoesler** [comment]
If you all could pull this down and do some testing as well - that would be great. I ran it multiple times last night for ~10 minutes a time. Want to make sure this isn't breaking something else unintentionally. Another reason for us to make some better tests using mocked time 😁

File: timeHelper.go [hunk 3]
```diff
@@ -3,7 +3,8 @@ package gocron
 import "time"
 
 type timeHelper interface {
-	Now() time.Time
+	Now(*time.Location) time.Time
+	NowRoundedDownToSeconds(*time.Location) time.Time
```
Comment (Streppel) [inline timeHelper.go:7]: another thought: as we don't consider nanoseconds anywhere in the project, what do you think about putting this logic in the Now() method and removing this one? Seems like a good idea?

Comment (JohnRoesler) [reply timeHelper.go:7]: Yeah I was thinking about that last night also. Glad you are validating it. I'll make that change as well.

**Comment by Streppel** [comment]
> If you all could pull this down and do some testing as well - that would be great. I ran it multiple times last night for ~10 minutes a time. Want to make sure this isn't breaking something else unintentionally. Another reason for us to make some better tests using mocked time grin

Doing it right now :)! Also I'll make some commits in this branch if you're ok with it

**Comment by JohnRoesler** [comment]
@Streppel go for it!

**Comment by Streppel** [comment]
@arjunmahishi any closing thoughts before we merge?

**Comment by arjunmahishi** [comment]
Nope.
