### PR TITLE
fix(scheduler): ensure negative intervals given to `Every` return an immediate error #600

### LINKED ISSUE #600: [BUG] - Handling negative time.Duration as interval param to `Every` func
### Describe the bug

Not sure if this is a bug, more of a question to confirm expected behavior: currently no error is returned when a negative `time.Duration` is provided as the interval param to `Every`. Is that intentional? Should it not return an error and fail fast, similar to when providing a negative int? Not clear to me what the intended behavior is for that.

### To Reproduce

```
scheduler := gocron.NewScheduler(time.UTC)
interval := -1 * time.Second
_, err := scheduler.Every(interval).Do(func() { })
```

### Version

v1.35.2

### Expected behavior

`err` is returned non-nil, or otherwise behavior for negative Duration is documented on the `Every` function.

### Additional context

Thinking it would be helpful as input validation to get an error in this scenario to immediately recognize invalid setup, just like how negative int values are treated as errors.

### PR DESCRIPTION
**Pull request by husam-e**
### What does this do?

Ensures negative intervals return an immediate error.

### Which issue(s) does this PR fix/relate to?
Resolves #600 

### List any changes that modify/break current functionality

Negative intervals will now return an error.

### Have you included tests for your changes?
Yes.

### Did you document any new/modified functionality?

- [ ] Updated `example_test.go`
- [ ] Updated `README.md`

### Notes

Potentially breaking change for any consumer expecting negative intervals to not return an error.

### CODE REVIEW

File: scheduler_test.go [hunk 1]
```diff
@@ -145,6 +145,12 @@ func TestScheduler_Every(t *testing.T) {
 		}
 		s.Stop()
 		assert.Equal(t, 6, counter)
+
+		_, err = s.Every(-1 * time.Millisecond).Do(func() {
+			// do nothing
+		})
+
+		require.EqualError(t, err, ErrInvalidInterval)
```
Comment (JohnRoesler) [inline scheduler_test.go]: > cannot use ErrInvalidInterval (variable of type error) as string value in argument to require.EqualError
```suggestion
		require.EqualError(t, err, ErrInvalidInterval.Error())
```

File: scheduler_test.go [hunk 2]
```diff
@@ -192,6 +198,12 @@ func TestScheduler_Every(t *testing.T) {
 		}
 		s.Stop()
 		assert.Equal(t, 2, counter)
+
+		_, err = s.Every("-1ms").Do(func() {
+			// do nothing
+		})
+
+		require.EqualError(t, err, ErrInvalidInterval)
```
Comment (husam-e) [inline scheduler_test.go]:
```suggestion
		require.EqualError(t, err, ErrInvalidInterval.Error())
```

File: scheduler_test.go [hunk 3]
```diff
@@ -145,6 +145,12 @@ func TestScheduler_Every(t *testing.T) {
 		}
 		s.Stop()
 		assert.Equal(t, 6, counter)
+
+		_, err = s.Every(-1 * time.Millisecond).Do(func() {
+			// do nothing
+		})
+
+		require.EqualError(t, err, ErrInvalidInterval.Error())
```
Comment (JohnRoesler) [inline scheduler_test.go]: ah, the error is wrapped. So it's got another one around it. I think using `require.ErrorIs` should do it

Comment (JohnRoesler) [inline scheduler_test.go]:
```suggestion
		require.ErrorIs(t, err, ErrInvalidInterval)
```

File: scheduler_test.go [hunk 4]
```diff
@@ -192,6 +198,12 @@ func TestScheduler_Every(t *testing.T) {
 		}
 		s.Stop()
 		assert.Equal(t, 2, counter)
+
+		_, err = s.Every("-1ms").Do(func() {
+			// do nothing
+		})
+
+		require.EqualError(t, err, ErrInvalidInterval.Error())
```
Comment (JohnRoesler) [inline scheduler_test.go]:
```suggestion
		require.ErrorIs(t, err, ErrInvalidInterval)
```

File: scheduler_test.go [hunk 5]
```diff
@@ -145,6 +145,12 @@ func TestScheduler_Every(t *testing.T) {
 		}
 		s.Stop()
 		assert.Equal(t, 6, counter)
+
+		_, err = s.Every(-1 * time.Millisecond).Do(func() {
+			// do nothing
+		})
+
+		require.ErrorIs(t, err, ErrInvalidInterval)
```
Comment (JohnRoesler) [inline scheduler_test.go]:
```suggestion
		require.Contains(t, err.Error(), ErrInvalidInterval.Error())
```

File: scheduler_test.go [hunk 6]
```diff
@@ -192,6 +198,12 @@ func TestScheduler_Every(t *testing.T) {
 		}
 		s.Stop()
 		assert.Equal(t, 2, counter)
+
+		_, err = s.Every("-1ms").Do(func() {
+			// do nothing
+		})
+
+		require.ErrorIs(t, err, ErrInvalidInterval)
```
Comment (JohnRoesler) [inline scheduler_test.go]:
```suggestion
		require.Contains(t, err.Error(), ErrInvalidInterval.Error())
```

**Review by JohnRoesler — APPROVED** [review]

File: scheduler_test.go (hunk 3 above)
Comment (husam-e) [reply scheduler_test.go]: thanks, I actually removed these checks as I realized there was already a bad interval test case, so I added cases to that and switched it to use contain.
