### PR TITLE
fix month duration calculation error

### LINKED ISSUE #294: [BUG] - panic: runtime error: integer divide by zero
Same as #282, another case.
```
package main

import (
	"time"

	"github.com/go-co-op/gocron"
)

func main() {
	s := gocron.NewScheduler(time.UTC)
	t := time.Date(2022, 1, 24, 0, 0, 0, 0, time.UTC)

	s.Every(1).Months(25).StartAt(t).Do(func() {})
	s.StartBlocking()
}
```
```
% go run -trimpath main.go
panic: runtime error: integer divide by zero

goroutine 1 [running]:
github.com/go-co-op/gocron.(*Scheduler).scheduleNextRun(0xc000110000, 0xc000112180)
        github.com/go-co-op/gocron@v1.12.1-0.20220214155418-2d070e5db0fe/scheduler.go:178 +0x572
github.com/go-co-op/gocron.(*Scheduler).Do(0xc000110000, {0x10bb860, 0x10daf88}, {0x0, 0x0, 0x0})
        github.com/go-co-op/gocron@v1.12.1-0.20220214155418-2d070e5db0fe/scheduler.go:806 +0x445
main.main()
        ./main.go:15 +0x265
exit status 2
```

### PR DESCRIPTION
**Pull request by xwjdsh**
### What does this do?
fix #294
### Have you included tests for your changes?
Yes.

### CODE REVIEW

File: scheduler.go [hunk 1]
```diff
@@ -295,7 +295,7 @@ func calculateNextRunForMonth(s *Scheduler, job *Job, lastRun time.Time, dayOfMo
 		next = next.AddDate(0, job.interval, -0)
 		next = next.Add(-difference)
 	} else {
-		if job.interval == 1 { // every month counts current month
+		if job.interval == 1 && !jobDay.Equal(lastRun) { // every month counts current month
```
Comment (JohnRoesler) [inline scheduler.go:298]:
```suggestion
		if job.interval == 1 && !jobDay.Equal(lastRun) { // every month counts current month 
```

File: scheduler.go [hunk 2]
```diff
@@ -295,7 +295,7 @@ func calculateNextRunForMonth(s *Scheduler, job *Job, lastRun time.Time, dayOfMo
...
```
Comment (JohnRoesler) [inline scheduler.go:298]:
```suggestion
		if job.interval == 1 && !jobDay.Equal(lastRun) { // every month counts current month
```

**Review by JohnRoesler — APPROVED** [review]
thank you!
