### PR TITLE
Fix: Handle job creation errors better

### LINKED ISSUE #84: [BUG] - Reflect panic with too many jobs possibly
### Describe the bug

reported by @Algalish

```
panic: reflect: call of reflect.Value.Type on zero Value

goroutine 44934 [running]:
reflect.Value.Type(0x0, 0x0, 0x0, 0x0, 0x175fdd5aee8)
        /usr/local/go/src/reflect/value.go:1877 +0x166
github.com/go-co-op/gocron.callJobFuncWithParams(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x175fe0375a8, 0x40fd526000000000, 0x0, 0x0)
       /projects/src/src/github.com/go-co-op/gocron/gocron.go:53 +0xc5
github.com/go-co-op/gocron.(*Job).run(0xc0000dc540)
        /projects/src/src/github.com/go-co-op/gocron/job.go:52 +0x13b
created by github.com/go-co-op/gocron.(*Scheduler).run
        /projects/src/src/github.com/go-co-op/gocron/scheduler.go:290 +0x3f
```

### To Reproduce

```
cronScheduler = gocron.NewScheduler(time.UTC)
	for h := 0; h < 24; h++ {
		for m := 0; m < 60; m += 20 {
			timeString := fmt.Sprint(h) + ":" + fmt.Sprint(m)
			cronScheduler.Every(1).Day().At(timeString).Do(getModDetails)
			log.Println(timeString)
		}
	}
```

### PR DESCRIPTION
**Pull request by arjunmahishi**
### What does this do?
Remove the placeholder job from the scheduler while returning any error from the `Do` function

### Which issue(s) does this PR fix/relate to?
Closes #84 

### Have you included tests for your changes?
Yes

### CODE REVIEW

File: scheduler_test.go [hunk 1]
```diff
@@ -846,3 +846,19 @@ func TestRunJobsWithLimit(t *testing.T) {
 	assert.Exactly(t, 1, j1Counter)
 	assert.Exactly(t, 1, j2Counter)
 }
+
+func TestErrorDuringJobCreation(t *testing.T) {
+	// error due to bad time format
+	badTime := "0:0"
+	s := NewScheduler(time.Local)
+	s.Every(1).Day().At(badTime).Do(func() {})
```
Comment (JohnRoesler) [inline scheduler_test.go:854]: Could we move this test case into the `At` func test?

File: scheduler_test.go [hunk 2]
```diff
@@ -846,3 +846,19 @@ func TestRunJobsWithLimit(t *testing.T) {
...
+	assert.Zero(t, len(s.jobs), "The job should be deleted if the time format is wrong")
+
+	// error due to the arg passed to Do() not being a function
+	s.Every(1).Second().Do(1)
```
Comment (JohnRoesler) [inline scheduler_test.go:858]: do we have a test for `Do`? I really like mapping tests directly to functions

File: scheduler_test.go (hunk 1 above)
Comment (arjunmahishi) [reply scheduler_test.go:854]: Done

File: scheduler_test.go (hunk 2 above)
Comment (arjunmahishi) [reply scheduler_test.go:858]: Come to think of it, this function (`TestErrorDuringJobCreation`) is actually testing `Do` function. So, I could rename this function `TestDo`.

**Review by Streppel — APPROVED** [review]

**Review by JohnRoesler — APPROVED** [review]
