### PR TITLE
issue-756: fix interface variadic parameters verifying

### LINKED ISSUE #756: [BUG] - cannot handle variadic interface parameters
This code does not work:

```go
func main() {
	j, err := s.NewJob(
		gocron.DurationJob(
			10*time.Second,
		),
		gocron.NewTask(
			func(parameters ...any) {
				for i := range parameters {
					fmt.Println(parameters[i])
				}
			},
			1,
			"2",
		),
	)
	if err != nil {
		panic(err)
	}
}
```
It panicked like this: 
image

This because the verifyVariadic only checks the first element's underlying type of `parameters ...any`, the first element's underlying type is `int` here and the second element's underlying type is `string`.

What I want: This code runs well without any panicking and keeps type-safe.

The correct behavior is that if the variadic parameter's type is interface, we only need to check if the actual parameters implement that interface.

I'd like to send a PR to fix this issue.

### PR DESCRIPTION
**Pull request by apocelipes**
Fixes #756.

### What does this do?
Check interface-implements if variadic parameter's types is an interface.

### Which issue(s) does this PR fix/relate to?
Resolves https://github.com/go-co-op/gocron/issues/756

### List any changes that modify/break current functionality
Nothing.

### Have you included tests for your changes?
Yes. I have added 2 test cases.

### Did you document any new/modified functionality?

- [x] Updated `scheduler_test.go`

### CODE REVIEW

File: scheduler_test.go [hunk 1]
```diff
@@ -924,6 +925,16 @@ func TestScheduler_NewJobTask(t *testing.T) {
 			NewTask(func(args ...interface{}) {}),
 			nil,
 		},
+		{
+			"all good no arguments passed in - interface variadic",
```
Comment (JohnRoesler) [inline scheduler_test.go]:
```suggestion
			"all good - interface variadic, int, string",
```

**Review by JohnRoesler — APPROVED** [review]
