### PR TITLE
issue-677: support task creation with variadic args

### LINKED ISSUE #677: [BUG] - Cannot create job with task with variadic args
### Describe the bug

When creating a job with a task that has variadic args, the validator in the library will expect the variadic args to be "1" argument (suspect to be a slice of that type). So creating a job with a task that has function of variadic arguments will always return `ErrNewJobWrongNumberOfParameters`. 

### To Reproduce

1. Create a function that has variadic args
2. Try create a cronjob from that

```go
scheduler, _ := gocron.NewScheduler()

myfunc := func(args ...string) {
  panic("This works")
}

// will have error
job, err := scheduler.NewJob(
  gocron.CronJob("* * * * 1", false),
  gocron.NewTask(myfunc), // the validator will expect num param to be 1 (slice of string)
)

```

### Version

v2.2.1

### Expected behavior

should be able to execute task with variadic parameters.

### PR DESCRIPTION
**Pull request by Higan**
### What does this do?
This pull request implements variadic args support for task creation

### Which issue(s) does this PR fix/relate to?

Resolves #677 

### Have you included tests for your changes?
I have added several cases in `scheduler_test.go` based on my changes

### Did you document any new/modified functionality?
- [x] Updated `scheduler_test.go`

### CODE REVIEW

File: scheduler.go [hunk 1]
```diff
@@ -535,6 +535,47 @@ func (s *scheduler) NewJob(jobDefinition JobDefinition, task Task, options ...Jo
 	return s.addOrUpdateJob(uuid.Nil, jobDefinition, task, options)
 }
 
+func (s *scheduler) verifyParameterType(taskFunc reflect.Value, tsk task) error {
+	isVariadic := taskFunc.Type().IsVariadic()
```
Comment (JohnRoesler) [inline scheduler.go]: 🚀 epic, i was poking around the other day but didn't notice this IsVariadic method

File: scheduler_test.go [hunk 2]
```diff
@@ -899,6 +899,26 @@ func TestScheduler_NewJobTask(t *testing.T) {
...
+			nil,
+		},
+		{
+			"all good struct - variadic",
+			NewTask(func(args ...interface{}) {}, struct{}{}),
+			nil,
+		},
+		{
+			"all good no arguments passed in - variadic",
+			NewTask(func(args ...interface{}) {}),
```
Comment (JohnRoesler) [inline scheduler_test.go:924]: could you add a test case with multiple argument types where the last one is variadic? 

something like
```golang
NewTask(func(arg int, args ...string) {}, 1, "one", "two")
```

Comment (Higan) [reply scheduler_test.go:924]: Sure this was neglected in my previous commit. And it's added now in this PR. Please have a look.

**Review by JohnRoesler — APPROVED** [review]
