### PR TITLE
fixes 38

### LINKED ISSUE #38: [BUG] - StartAsync creates infinite schedulers
### Describe the bug

Calling `StartAsync` repeatedly causes a mem leak due to the neverstopping ticker and causes many concorrent runs on RunPending.

### PR DESCRIPTION
**Pull request by Streppel**
fixes #38

### CODE REVIEW

File: scheduler.go [hunk 1]
```diff
@@ -32,22 +38,26 @@ func (s *Scheduler) StartBlocking() {
...
+			case <-s.stopChan:
 				ticker.Stop()
+				s.running = false
 				return
 			}
 		}
 	}()
 
-	return stopped
+	return s.stopChan
```
Comment (arjunmahishi) [inline scheduler.go:60]: (Unrated to this PR) Do we really need to expose this `chan` to the user? We already have a `s.Stop()` that takes care of stopping the scheduler.

Comment (Streppel) [reply scheduler.go:60]: You're absolutely right, but as this would a breaking change I decided to leave it for another PR
