### PR TITLE
Fix panic err job create before set behaviour.

### LINKED ISSUE #230: [BUG] - Scheduling a job and calling get current job before every/cron panics
### Describe the bug

When scheduling a job, if I call a func that calls `getCurrentJob()` prior to the `newJob()` func being called, a slice index panic occurs.

### To Reproduce

```go
s := gocron.NewScheduler(time.UTC)
s.WaitForSchedule().Every("1m").Do(func() {})
```

output:
```
panic: runtime error: index out of range [-1]
```

### Version

v1.7.1

### Expected behavior

the panic should be handled through a slice bounds check and surfaced to the caller

### Additional context

The solution should be generic to catch / handle an error anytime a func is called prior to the instantiation of a job. 

Couple options:

1. Continue to enforce the Every/Cron methods be called first and catch the error

2. Allow methods to be called in any order, causing a new job to be created by whichever func is called first.

I like the 2nd approach better, and actually I think a bit of redesign here to think of this like a chain could be good allowing any order and the creation of a job to occur as implicitly in the first link of the chain.

### PR DESCRIPTION
**Pull request by denizzengin**
### What does this do?
fix panic error  and can be set behaviour before new job created.

### Which issue(s) does this PR fix/relate to?
Resolve #230

### Did you document any new/modified functionality?

- [x] Updated `example_test.go`
- [ ] Updated `README.md`

### CODE REVIEW

**Comment by denizzengin** [comment]
hi @JohnRoesler , 
What do you think above solution ? 
it's more generic than  my first solution.

File: scheduler.go [hunk 1]
```diff
@@ -977,6 +981,11 @@ func (s *Scheduler) Sunday() *Scheduler {
 }
 
 func (s *Scheduler) getCurrentJob() *Job {
+	if len(s.jobs) == 0 {
```
Comment (JohnRoesler) [inline scheduler.go:984]:
```suggestion
	if len(s.Jobs()) == 0 {
```

File: scheduler.go [hunk 2]
```diff
@@ -977,6 +981,11 @@ func (s *Scheduler) Sunday() *Scheduler {
...
+		job := &Job{}
+		s.setJobs(append(s.Jobs(), job))
```
Comment (JohnRoesler) [inline scheduler.go:986]:
```suggestion
		s.setJobs([]*Job{{}})
```

File: scheduler.go [hunk 3]
```diff
@@ -30,9 +30,10 @@ type Scheduler struct {
 
 	tags sync.Map // for storing tags when unique tags is set
 
-	tagsUnique      bool // defines whether tags should be unique
-	updateJob       bool // so the scheduler knows to create a new job or update the current
-	waitForInterval bool // defaults jobs to waiting for first interval to start
+	tagsUnique                     bool // defines whether tags should be unique
+	updateJob                      bool // so the scheduler knows to create a new job or update the current
+	waitForInterval                bool // defaults jobs to waiting for first interval to start
+	isSetBehaviourBeforeJobCreated bool // represents if set some feature before job created
```
Comment (JohnRoesler) [inline scheduler.go:36]:
```suggestion
	tagsUnique      bool // defines whether tags should be unique
	updateJob       bool // so the scheduler knows to create a new job or update the current
	waitForInterval bool // defaults jobs to waiting for first interval to start
	jobCreated      bool // so the scheduler knows a job was created prior to calling Every or Cron
```

Comment (JohnRoesler) [reply scheduler.go:36]: @denizzengin if you can make this change and refactor all the references, then I'll approve!

Comment (denizzengin) [reply scheduler.go]: @JohnRoesler  it's done but there is a test error but i run local tests successfully - (with make test)
Actually, my changes don't releated with TestScheduler_SetMaxConcurrentJobs method but gave error. i don't know what's going on here. Any suggestion ?

**Review by JohnRoesler — APPROVED** [review]

File: scheduler.go (hunk 3 above)
Comment (JohnRoesler) [reply scheduler.go]: occaisionally tests fail due to timing / slowness in the docker containers that actions uses. I've been meaning to open an issue for us to refactor the tests to use a minimum of 1 second duration because I have some that use milliseconds interval in testing and it's not reliable in the actions pipeline

**Comment by JohnRoesler** [comment]
@denizzengin thanks for the contribution! ❤️
