### PR TITLE
fix: stopping scheduler waits for all jobs to finish

### LINKED ISSUE #237: [BUG] - Scheduler should wait all jobs to finish before returning .Stop()
### Describe the bug

Scheduler should wait all jobs to finish before returning .Stop()

### To Reproduce

```go
i := 0
s := NewScheduler(time.UTC)
s.Every(1).Second().Do(func() {
	time.Sleep(2 * time.Second)
	i = 1
})
s.StartAsync()
time.Sleep(1 * time.Second) // time to ignite job
s.Stop()
// on this line variable i should be 1 
```

### Version

v1.8.0

### PR DESCRIPTION
**Pull request by Streppel**
### What does this do?

Scheduler now waits for all running jobs to finish before returning. Fixes #237. 

### Which issue(s) does this PR fix/relate to?
Fixes #237 

### List any changes that modify/break current functionality
None.

### Have you included tests for your changes?
Yes.

### Did you document any new/modified functionality?
Yes.
- [ ] Updated `example_test.go`
- [ ] Updated `README.md`

### CODE REVIEW

File: scheduler.go [hunk 1]
```diff
@@ -698,7 +699,7 @@ func (s *Scheduler) Stop() {
 
 func (s *Scheduler) stop() {
 	s.setRunning(false)
-	s.executor.stop <- struct{}{}
+	s.executor.stop()
```
[the remark this answers is not in the document]
Comment (Streppel) [reply scheduler.go:702]: oh, this is the .stop() from executor, not the scheduler itself!

**Review by JohnRoesler — APPROVED** [review]
very nice

File: scheduler_test.go [hunk 2]
```diff
@@ -631,6 +631,19 @@ func TestScheduler_Stop(t *testing.T) {
 		s.Stop()
 		assert.False(t, s.IsRunning())
 	})
+	t.Run("waits for jobs to finish processing before returning .Stop()", func(t *testing.T) {
+		t.Parallel()
+		i := 0
+		s := NewScheduler(time.UTC)
+		s.Every(1).Second().Do(func() {
+			time.Sleep(2 * time.Second)
+			i = 1
```
Comment (JohnRoesler) [inline scheduler_test.go:640]: this is creating a race condition. you could as atomic int, or mutex for I here, or our semaphore pattern

Comment (JohnRoesler) [reply scheduler_test.go:640]: or no, this has to do with the stop method

File: executor.go [hunk 3]
```diff
@@ -92,10 +95,14 @@ func (e *executor) start() {
...
-		case <-e.stop:
+		case <-e.stopCh:
 			cancel()
-			wg.Wait()
 			return
 		}
 	}
 }
+
+func (e executor) stop() {
```
Comment (JohnRoesler) [inline executor.go:105]: any reason for this to be a non-pointer `executor` vs `e *executor`?

File: scheduler_test.go [hunk 4]
```diff
@@ -631,6 +631,19 @@ func TestScheduler_Stop(t *testing.T) {
...
+		// i := 0
+		s := NewScheduler(time.UTC)
+		s.Every(1).Second().Do(func() {
+			time.Sleep(2 * time.Second)
+			// i = 1
+		})
+		s.StartAsync()
+		time.Sleep(1 * time.Second) // enough time for job to run
+		s.Stop()
+		assert.Equal(t, 1, 1)
```
Comment (JohnRoesler) [inline scheduler_test.go:645]: 1 will always equal 1 lol

**Review by JohnRoesler — APPROVED** [review]
