### PR TITLE
fix RunNow() when calling from a job returned by Jobs()

### LINKED ISSUE #667: BUG: gocron: Job: RunNow: scheduler unreachable
### Discussed in https://github.com/go-co-op/gocron/discussions/666

<div type='discussions-op-text'>

<sup>Originally posted by **kishenpatel** February  1, 2024</sup>
Hey team! I am trying to leverage the job .RunNow() command but even with the simplest implementation I seem to get the error "gocron: Job: RunNow: scheduler unreachable", please see example code below and please let me know if I might be doing something wrong?

```go
package main

import (
	"fmt"
	"time"

	"github.com/go-co-op/gocron/v2"
)

func main() {
	fmt.Println("Hello, 世界")

	sch, err := gocron.NewScheduler()
	if err != nil {
		fmt.Println("Failed to create new scheduler")
		fmt.Print(err)
		return
	}

	_, err = sch.NewJob(
		gocron.DurationJob(
			30*time.Second,
		),
		gocron.NewTask(
			func(a string, b int) {
				fmt.Println(a, b)
			},
			"hello",
			1,
		),
	)
	if err != nil {
		fmt.Println("Failed to add job")
		fmt.Print(err)
		return
	}
	fmt.Println("Successfully added job")

	sch.Start()

	jobs := sch.Jobs()
	j0 := jobs[0]
	err = j0.RunNow()
	if err != nil {
		fmt.Println("Failed to run job")
		fmt.Print(err)
	}
}

``` 

Playground:
https://go.dev/play/p/6MMUrYTeZDX

Please advise! Thank you!</div>

### PR DESCRIPTION
**Pull request by JohnRoesler**
### What does this do?
Jobs() needs to return the run now channel in order to enable jobs to use RunNow

### Which issue(s) does this PR fix/relate to?

resolves #667 

### Did you document any new/modified functionality?

- [ ] Updated `example_test.go`
- [ ] Updated `README.md`

### CODE REVIEW

File: scheduler.go [hunk 1]
```diff
@@ -454,10 +454,11 @@ func (s *scheduler) now() time.Time {
...
 	return job{
-		id:            in.id,
-		name:          in.name,
-		tags:          slices.Clone(in.tags),
-		jobOutRequest: s.jobOutRequestCh,
+		in.id,
+		in.name,
+		slices.Clone(in.tags),
+		s.jobOutRequestCh,
+		s.runJobRequestCh,
```
Comment (JohnRoesler) [inline scheduler.go:461]: switched this to not used named struct parameters so a future build will break if a new field is added to job but not populated here

File: scheduler_test.go [hunk 2]
```diff
@@ -1529,9 +1529,10 @@ func TestScheduler_RunJobNow(t *testing.T) {
 		t.Run(tt.name, func(t *testing.T) {
 			s := newTestScheduler(t)
 
-			j, err := s.NewJob(tt.j, NewTask(tt.fun), tt.opts...)
+			_, err := s.NewJob(tt.j, NewTask(tt.fun), tt.opts...)
 			require.NoError(t, err)
 
+			j := s.Jobs()[0]
```
Comment (JohnRoesler) [inline scheduler_test.go:1535]: updating this test to validate the exact behavior seen in the issue.
